export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  LOAD_POPULAR_REFRESH_FAIL: 'LOAD_POPULAR_REFRESH_FAIL',
  LOAD_POPULAR_REFRESH_SUCCESS: 'LOAD_POPULAR_REFRESH_SUCCESS',
};
